name: call sheet generator
version: "0.10"
summary: JSpdf powered call sheet generator for photo shoots/productions ina snap
description: a JSpdf powered call sheet generator for photo shoots/productions 
    to get everything organized into a handy PDF for email to PA and the rest of production
grade: devmode
confinement: strict
